package codegen

import (
	"encoding/base64"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"github.com/meoyawn/clickgen/internal/chtype"
	"github.com/meoyawn/clickgen/internal/parser"
	"github.com/meoyawn/clickgen/internal/schema"
)

type QuerySpec struct {
	Query  parser.Query
	Result []schema.Column
}

type Options struct {
	PackageName string
	Overrides   chtype.Overrides
}

type paramModel struct {
	OriginalName string
	FieldName    string
	LocalName    string
	CHType       string
	GoType       string
}

type fieldModel struct {
	OriginalName string
	FieldName    string
	CHType       string
	GoType       string
	Nullable     bool
}

type queryModel struct {
	OriginalName  string
	MethodName    string
	ConstName     string
	RowType       string
	RowName       string
	ShouldEmitRow bool
	Kind          parser.Command
	SQL           string
	Params        []paramModel
	Fields        []fieldModel
}

func Generate(opts Options, specs []QuerySpec) ([]byte, error) {
	if opts.PackageName == "" {
		opts.PackageName = "generated"
	}
	if len(specs) == 0 {
		return nil, fmt.Errorf("no queries to generate")
	}

	models := make([]queryModel, 0, len(specs))
	imports := map[string]struct{}{
		"context": {},
		"github.com/ClickHouse/clickhouse-go/v2/lib/driver": {},
	}
	needsParams := false

	for _, spec := range specs {
		model, modelImports, usesParams, err := buildModel(spec, opts.Overrides)
		if err != nil {
			return nil, err
		}
		for path := range modelImports {
			imports[path] = struct{}{}
		}
		if usesParams {
			needsParams = true
		}
		models = append(models, model)
	}
	if err := assignSharedRows(models); err != nil {
		return nil, err
	}
	if needsParams {
		imports["github.com/ClickHouse/clickhouse-go/v2"] = struct{}{}
	}
	formatters := collectQueryParameterFormatters(models, opts.Overrides)
	for path := range formatters.imports {
		imports[path] = struct{}{}
	}

	var b strings.Builder
	b.WriteString("// Code generated by clickgen. DO NOT EDIT.\n\n")
	b.WriteString("package ")
	b.WriteString(opts.PackageName)
	b.WriteString("\n\n")
	writeImports(&b, imports)
	writeCommon(&b)
	if needsParams {
		formatters.write(&b)
	}
	for _, model := range models {
		writeQuery(&b, model, &formatters)
	}

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w\n%s", err, b.String())
	}
	return formatted, nil
}

func buildModel(spec QuerySpec, overrides chtype.Overrides) (queryModel, map[string]struct{}, bool, error) {
	query := spec.Query
	model := queryModel{
		OriginalName:  query.Name,
		MethodName:    exportedIdentifier(query.Name),
		ConstName:     unexportedIdentifier(query.Name) + "SQL",
		RowName:       exportedIdentifier(query.Name) + "Row",
		ShouldEmitRow: true,
		Kind:          query.Cmd,
		SQL:           query.SQL,
	}
	imports := map[string]struct{}{}
	if query.RowType != "" {
		if query.Cmd == parser.CommandExec {
			return model, nil, false, fmt.Errorf("query %s uses row=%s with :exec; row is only supported for result queries", query.Name, query.RowType)
		}
		model.RowType = exportedIdentifier(query.RowType)
		if model.RowType == "" {
			return model, nil, false, fmt.Errorf("query %s has invalid row pragma %q", query.Name, query.RowType)
		}
	}

	for _, param := range query.Params {
		goType := chtype.Map(param.ClickHouseType, overrides)
		for path := range goType.Imports {
			imports[path] = struct{}{}
		}
		param := paramModel{
			OriginalName: param.Name,
			FieldName:    exportedIdentifier(param.Name),
			LocalName:    safeLocalName(unexportedIdentifier(param.Name)),
			CHType:       param.ClickHouseType,
			GoType:       goType.Name,
		}
		model.Params = append(model.Params, param)
	}

	if query.Cmd != parser.CommandExec {
		if len(spec.Result) == 0 {
			return model, nil, false, fmt.Errorf("query %s requires result schema for :%s", query.Name, query.Cmd)
		}
		usedFields := map[string]int{}
		for idx, column := range spec.Result {
			goType := chtype.Map(column.ClickHouseType, overrides)
			for path := range goType.Imports {
				imports[path] = struct{}{}
			}
			fieldName := exportedIdentifier(column.Name)
			if fieldName == "" {
				fieldName = fmt.Sprintf("Column%d", idx+1)
			}
			fieldName = uniqueName(fieldName, usedFields)
			model.Fields = append(model.Fields, fieldModel{
				OriginalName: column.Name,
				FieldName:    fieldName,
				CHType:       column.ClickHouseType,
				GoType:       goType.Name,
				Nullable:     chtype.IsNullable(column.ClickHouseType),
			})
		}
	}

	return model, imports, len(model.Params) > 0, nil
}

type sharedRowShape struct {
	QueryName string
	Fields    []sharedRowField
}

type sharedRowField struct {
	OriginalName string
	FieldName    string
	GoType       string
	Nullable     bool
}

func assignSharedRows(models []queryModel) error {
	seen := map[string]sharedRowShape{}
	for idx := range models {
		model := &models[idx]
		if model.RowType == "" || len(model.Fields) <= 1 {
			continue
		}

		model.RowName = model.RowType + "Row"
		shape := makeSharedRowShape(*model)
		prev, ok := seen[model.RowType]
		if !ok {
			seen[model.RowType] = shape
			continue
		}
		if diff := compareSharedRowShape(prev, shape); diff != "" {
			return fmt.Errorf("row=%s used by incompatible queries %s and %s: %s", model.RowType, prev.QueryName, model.MethodName, diff)
		}
		model.ShouldEmitRow = false
	}
	return nil
}

func makeSharedRowShape(model queryModel) sharedRowShape {
	fields := make([]sharedRowField, 0, len(model.Fields))
	for _, field := range model.Fields {
		fields = append(fields, sharedRowField{
			OriginalName: field.OriginalName,
			FieldName:    field.FieldName,
			GoType:       field.GoType,
			Nullable:     field.Nullable,
		})
	}
	return sharedRowShape{QueryName: model.MethodName, Fields: fields}
}

func compareSharedRowShape(want, got sharedRowShape) string {
	if len(want.Fields) != len(got.Fields) {
		return fmt.Sprintf("column count differs: %s has %d columns, %s has %d columns",
			want.QueryName, len(want.Fields), got.QueryName, len(got.Fields))
	}
	for idx := range want.Fields {
		if want.Fields[idx] == got.Fields[idx] {
			continue
		}
		return fmt.Sprintf("column %d differs: %s has %s, %s has %s",
			idx+1, want.QueryName, describeSharedRowField(want.Fields[idx]), got.QueryName, describeSharedRowField(got.Fields[idx]))
	}
	return ""
}

func describeSharedRowField(field sharedRowField) string {
	return fmt.Sprintf("name=%q field=%s type=%s nullable=%t", field.OriginalName, field.FieldName, field.GoType, field.Nullable)
}

func writeImports(b *strings.Builder, imports map[string]struct{}) {
	paths := make([]string, 0, len(imports))
	for path := range imports {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	b.WriteString("import (\n")
	for _, path := range paths {
		b.WriteString("\t")
		b.WriteString(strconv.Quote(path))
		b.WriteString("\n")
	}
	b.WriteString(")\n\n")
}

func writeCommon(b *strings.Builder) {
	b.WriteString(`type DBQuerier interface {
	Query(ctx context.Context, query string, args ...any) (driver.Rows, error)
	QueryRow(ctx context.Context, query string, args ...any) driver.Row
	Exec(ctx context.Context, query string, args ...any) error
}

`)
}

func writeQuery(b *strings.Builder, model queryModel, formatters *queryParameterFormatterRegistry) {
	writeMetadata(b, model)
	b.WriteString("const ")
	b.WriteString(model.ConstName)
	b.WriteString(" = ")
	b.WriteString(strconv.Quote(model.SQL))
	b.WriteString("\n\n")

	if len(model.Params) >= 3 {
		writeParamsStruct(b, model)
	}
	if len(model.Fields) > 0 && model.ShouldEmitRow {
		writeRow(b, model)
	}
	if len(model.Params) > 0 {
		writeArgsHelper(b, model, formatters)
	}
	writeMethod(b, model)
}

func writeMetadata(b *strings.Builder, model queryModel) {
	enc := base64.StdEncoding.EncodeToString
	b.WriteString("// clickgen:query\t")
	b.WriteString(model.OriginalName)
	b.WriteString("\t")
	b.WriteString(string(model.Kind))
	b.WriteString("\t")
	b.WriteString(enc([]byte(model.SQL)))
	b.WriteString("\n")
	for _, param := range model.Params {
		b.WriteString("// clickgen:param\t")
		b.WriteString(model.OriginalName)
		b.WriteString("\t")
		b.WriteString(param.OriginalName)
		b.WriteString("\t")
		b.WriteString(enc([]byte(param.CHType)))
		b.WriteString("\t")
		b.WriteString(enc([]byte(param.GoType)))
		b.WriteString("\n")
	}
	for _, field := range model.Fields {
		b.WriteString("// clickgen:result\t")
		b.WriteString(model.OriginalName)
		b.WriteString("\t")
		b.WriteString(field.OriginalName)
		b.WriteString("\t")
		b.WriteString(enc([]byte(field.CHType)))
		b.WriteString("\t")
		b.WriteString(enc([]byte(field.GoType)))
		b.WriteString("\n")
	}
}

func writeParamsStruct(b *strings.Builder, model queryModel) {
	b.WriteString("type ")
	b.WriteString(model.MethodName)
	b.WriteString("Params struct {\n")
	for _, param := range model.Params {
		b.WriteString("\t")
		b.WriteString(param.FieldName)
		b.WriteString(" ")
		b.WriteString(param.GoType)
		b.WriteString(" `json:\"")
		b.WriteString(param.OriginalName)
		b.WriteString("\"`\n")
	}
	b.WriteString("}\n\n")
}

func writeRow(b *strings.Builder, model queryModel) {
	b.WriteString("type ")
	b.WriteString(model.RowName)
	b.WriteString(" struct {\n")
	for _, field := range model.Fields {
		b.WriteString("\t")
		b.WriteString(field.FieldName)
		b.WriteString(" ")
		b.WriteString(field.GoType)
		b.WriteString(" `json:\"")
		b.WriteString(field.OriginalName)
		b.WriteString("\" ch:\"")
		b.WriteString(field.OriginalName)
		b.WriteString("\"`\n")
	}
	b.WriteString("}\n\n")
}

func writeArgsHelper(b *strings.Builder, model queryModel, formatters *queryParameterFormatterRegistry) {
	if len(model.Params) >= 3 {
		b.WriteString("func (p ")
		b.WriteString(model.MethodName)
		b.WriteString("Params) args() clickhouse.Parameters {\n")
		b.WriteString("\treturn clickhouse.Parameters{\n")
		for _, param := range model.Params {
			b.WriteString("\t\t")
			b.WriteString(strconv.Quote(param.OriginalName))
			b.WriteString(": ")
			b.WriteString(formatters.valueExpr(param.CHType, "p."+param.FieldName))
			b.WriteString(",\n")
		}
		b.WriteString("\t}\n")
		b.WriteString("}\n\n")
		return
	}

	b.WriteString("func ")
	b.WriteString(unexportedIdentifier(model.OriginalName))
	b.WriteString("Args(")
	for idx, param := range model.Params {
		if idx > 0 {
			b.WriteString(", ")
		}
		b.WriteString(param.LocalName)
		b.WriteString(" ")
		b.WriteString(param.GoType)
	}
	b.WriteString(") clickhouse.Parameters {\n")
	b.WriteString("\treturn clickhouse.Parameters{\n")
	for _, param := range model.Params {
		b.WriteString("\t\t")
		b.WriteString(strconv.Quote(param.OriginalName))
		b.WriteString(": ")
		b.WriteString(formatters.valueExpr(param.CHType, param.LocalName))
		b.WriteString(",\n")
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")
}

func writeMethod(b *strings.Builder, model queryModel) {
	b.WriteString("func ")
	b.WriteString(methodSignature(model, true))
	b.WriteString(" {\n")
	writeArgsAssignment(b, model)

	switch model.Kind {
	case parser.CommandExec:
		b.WriteString("\treturn db.Exec(ctx, ")
		b.WriteString(model.ConstName)
		b.WriteString(")\n")
	case parser.CommandOne:
		b.WriteString("\tvar row ")
		b.WriteString(model.RowName)
		b.WriteString("\n")
		b.WriteString("\tif err := db.QueryRow(ctx, ")
		b.WriteString(model.ConstName)
		b.WriteString(").ScanStruct(&row); err != nil {\n")
		if len(model.Fields) == 1 {
			b.WriteString("\t\tvar zero ")
			b.WriteString(model.Fields[0].GoType)
			b.WriteString("\n\t\treturn zero, err\n")
		} else {
			b.WriteString("\t\treturn ")
			b.WriteString(model.RowName)
			b.WriteString("{}, err\n")
		}
		b.WriteString("\t}\n")
		if len(model.Fields) == 1 {
			b.WriteString("\treturn row.")
			b.WriteString(model.Fields[0].FieldName)
			b.WriteString(", nil\n")
		} else {
			b.WriteString("\treturn row, nil\n")
		}
	case parser.CommandMany:
		b.WriteString("\trows, err := db.Query(ctx, ")
		b.WriteString(model.ConstName)
		b.WriteString(")\n")
		b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
		b.WriteString("\tdefer rows.Close()\n\n")
		b.WriteString("\tvar out []")
		b.WriteString(model.RowName)
		b.WriteString("\n")
		b.WriteString("\tfor rows.Next() {\n")
		b.WriteString("\t\tvar row ")
		b.WriteString(model.RowName)
		b.WriteString("\n")
		b.WriteString("\t\tif err := rows.ScanStruct(&row); err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
		b.WriteString("\t\tout = append(out, row)\n")
		b.WriteString("\t}\n")
		b.WriteString("\tif err := rows.Err(); err != nil {\n\t\treturn nil, err\n\t}\n")
		b.WriteString("\treturn out, nil\n")
	}
	b.WriteString("}\n\n")
}

func writeArgsAssignment(b *strings.Builder, model queryModel) {
	switch {
	case len(model.Params) == 0:
		return
	case len(model.Params) >= 3:
		b.WriteString("\tctx = clickhouse.Context(ctx, clickhouse.WithParameters(params.args()))\n")
	default:
		b.WriteString("\tctx = clickhouse.Context(ctx, clickhouse.WithParameters(")
		b.WriteString(unexportedIdentifier(model.OriginalName))
		b.WriteString("Args(")
		for idx, param := range model.Params {
			if idx > 0 {
				b.WriteString(", ")
			}
			b.WriteString(param.LocalName)
		}
		b.WriteString(")))\n")
	}
}

func methodSignature(model queryModel, includeName bool) string {
	var b strings.Builder
	if includeName {
		b.WriteString(model.MethodName)
	}
	b.WriteString("(")
	b.WriteString("ctx context.Context, db DBQuerier")
	if len(model.Params) >= 3 {
		b.WriteString(", params ")
		b.WriteString(model.MethodName)
		b.WriteString("Params")
	} else {
		for _, param := range model.Params {
			b.WriteString(", ")
			b.WriteString(param.LocalName)
			b.WriteString(" ")
			b.WriteString(param.GoType)
		}
	}
	b.WriteString(") ")
	b.WriteString(returnSignature(model))
	return b.String()
}

func returnSignature(model queryModel) string {
	switch model.Kind {
	case parser.CommandExec:
		return "error"
	case parser.CommandMany:
		return "([]" + model.RowName + ", error)"
	case parser.CommandOne:
		if len(model.Fields) == 1 {
			return "(" + model.Fields[0].GoType + ", error)"
		}
		return "(" + model.RowName + ", error)"
	default:
		return "error"
	}
}

var goInitialisms = map[string]string{
	"api":   "API",
	"db":    "DB",
	"http":  "HTTP",
	"https": "HTTPS",
	"id":    "ID",
	"ip":    "IP",
	"sql":   "SQL",
	"url":   "URL",
	"uuid":  "UUID",
}

var reservedLocalNames = map[string]struct{}{
	"break": {}, "case": {}, "chan": {}, "const": {}, "continue": {}, "default": {},
	"defer": {}, "else": {}, "fallthrough": {}, "for": {}, "func": {}, "go": {},
	"goto": {}, "if": {}, "import": {}, "interface": {}, "map": {}, "package": {},
	"range": {}, "return": {}, "select": {}, "struct": {}, "switch": {}, "type": {},
	"var": {}, "ctx": {}, "err": {}, "out": {}, "params": {}, "q": {}, "query": {},
	"row": {}, "rows": {}, "db": {},
}

func exportedIdentifier(input string) string {
	return toIdentifier(input, true)
}

func unexportedIdentifier(input string) string {
	return toIdentifier(input, false)
}

func toIdentifier(input string, exported bool) string {
	words := splitWords(input)
	if len(words) == 0 {
		return ""
	}
	var b strings.Builder
	for idx, word := range words {
		lower := strings.ToLower(word)
		part, initialism := goInitialisms[lower]
		if idx == 0 && !exported {
			if initialism {
				b.WriteString(lower)
			} else {
				b.WriteString(lower[:1])
				if len(lower) > 1 {
					b.WriteString(lower[1:])
				}
			}
			continue
		}
		if initialism {
			b.WriteString(part)
			continue
		}
		b.WriteString(strings.ToUpper(lower[:1]))
		if len(lower) > 1 {
			b.WriteString(lower[1:])
		}
	}
	out := b.String()
	if out == "" {
		return out
	}
	if unicode.IsDigit([]rune(out)[0]) {
		if exported {
			return "N" + out
		}
		return "n" + out
	}
	return out
}

func splitWords(input string) []string {
	var words []string
	var current []rune
	runes := []rune(input)
	flush := func() {
		if len(current) > 0 {
			words = append(words, string(current))
			current = nil
		}
	}
	for idx, r := range runes {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			flush()
			continue
		}
		if len(current) > 0 && unicode.IsUpper(r) {
			prev := current[len(current)-1]
			nextLower := idx+1 < len(runes) && unicode.IsLower(runes[idx+1])
			if unicode.IsLower(prev) || unicode.IsDigit(prev) || (unicode.IsUpper(prev) && nextLower) {
				flush()
			}
		}
		current = append(current, r)
	}
	flush()
	return words
}

func safeLocalName(name string) string {
	if name == "" {
		return "value"
	}
	if _, ok := reservedLocalNames[name]; ok {
		return name + "_"
	}
	return name
}

func uniqueName(name string, used map[string]int) string {
	count := used[name]
	used[name] = count + 1
	if count == 0 {
		return name
	}
	return fmt.Sprintf("%s%d", name, count+1)
}
